# Generated by Django 4.1.2 on 2022-10-16 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_houseowner'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('INTERN', 'Intern')], max_length=30),
        ),
        migrations.CreateModel(
            name='RentAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_type', models.CharField(blank=True, choices=[('RENT', 'Rent'), ('FUNDED', 'Funded')], default='Rent', max_length=30, null=True)),
                ('city', models.CharField(max_length=50)),
                ('rooms', models.PositiveIntegerField()),
                ('rent', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.houseowner')),
            ],
        ),
    ]
